### ISSUE TITLE
Use Ansible role "template" files instead of custom sed replacement

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#170]
We need to have a look at the [template](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html) built-in feature and see how we could use is instead of using `sed`:

```
- name: "Create the OperatorHub subscription for {{ gpu_operator_csv_name }}"
  shell:
    set -o pipefail;
    cat {{ gpu_operator_operatorhub_sub }}
    | sed 's|{{ '{{' }} startingCSV {{ '}}' }}|{{ gpu_operator_csv_name }}|'
    | oc apply -f-
  args:
    warn: false # don't warn about using sed here
```
This change was "anticipated", as we already use the `jinga2` remplate style for our template files, eg:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gpu-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "{{ startingCSV }}"
```
---
**Example:**
```
- name: Store the CSV version
  set_fact:
    startingCSV: "{{ gpu_operator_csv_name }}"

- name: "Create the OperatorHub subscription for {{ gpu_operator_csv_name }}"
  template:
    src: "{{ gpu_operator_operatorhub_sub }}"
    dest: "{{ artifact_extra_logs_dir }}/gpu_operator_sub.yml"
```

---

**TODO**: List of the roles with `sed` transformation removed:

- [ ] `nfd_deploy`
- [ ] `local-ci_deploy`
- [ ] `gpu_operator_run_gpu-burn`
- [ ] `gpu_operator_deploy_custom_commit`
- [x] `gpu_operator_deploy_from_operatorhub`
