### ISSUE TITLE
ci-artifacts as a PSAP toolbox

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#34]
This issue tracks the progress of the PSAP [`toolbox`](https://github.com/openshift-psap/ci-artifacts/tree/master/toolbox):

GPU Operator
------------------

- [x] Deploy from OperatorHub
    - [ ] allow deploying an older version https://github.com/openshift-psap/ci-artifacts/issues/76
```
toolbox/gpu-operator/deploy_from_operatorhub.sh
toolbox/gpu-operator/undeploy_from_operatorhub.sh
```

- [x] Deploy from helm
```
toolbox/gpu-operator/list_version_from_helm.sh
toolbox/gpu-operator/deploy_with_helm.sh <helm-version>
toolbox/gpu-operator/undeploy_with_helm.sh
```

- [x]  Deploy from a custom commit. 
```
toolbox/gpu-operator/deploy_from_commit.sh <git repository> <git reference> [gpu_operator_image_tag_uid]
Example: 
toolbox/gpu-operator/deploy_from_commit.sh https://github.com/NVIDIA/gpu-operator.git master
```

- [x] Run the GPU Operator deployment validation tests
```
toolbox/gpu-operator/run_ci_checks.sh
```

- [ ] Run GPU Burst to validate that the GPUs can run workloads

- [ ] Capture GPU operator possible issues (entitlement, NFD labelling, operator deployment, state of resources in gpu-operator-resources, ...)
  - already partly done inside the CI, but we should improve the toolbox aspect

NFD
-----

- [ ]  Deploy the NFD operator from OperatorHub:
```
toolbox/nfd/deploy_from_operatorhub.sh
toolbox/nfd/undeploy_from_operatorhub.sh
```
  - [ ]  Control the channel to use from the command-line

- [ ] Test the NFD deployment #78
  - [ ] test with the NFD if GPU nodes are available
  - [ ] wait with the NFD for GPU nodes to become available  #78
```
toolbox/nfd/has_gpu_nodes.sh
toolbox/nfd/wait_gpu_nodes.sh
```

Cluster
---------

- [x] Add a GPU node on AWS
```
./toolbox/scaleup_cluster.sh
```
   - [x] Specify a machine type in the command-line, and skip scale-up if a node with the given machine-type is already present
```
./toolbox/scaleup_cluster.sh <machine-type>
```

- [x] Entitle the cluster, by passing a PEM file, checking if they should be concatenated or not, etc. And do nothing is the cluster is already entitled
```
toolbox/entitlement/deploy.sh --pem /path/to/pem
toolbox/entitlement/deploy.sh --machine-configs /path/to/machineconfigs
toolbox/entitlement/undeploy.sh
toolbox/entitlement/test.sh
toolbox/entitlement/wait.sh
```
  - [x] Capture all the clues required to understand entitlement issues 

```
toolbox/entitlement/inspect.sh
```

- [ ] Deployment of an entitled cluster 
  - already coded, but we need to integrate [this repo](https://gitlab.com/kpouget_psap/deploy-cluster) within the toolbox
  - deploy a cluster with 1 master node

CI
---

- [x] Build the image used for the Prow CI testing, and run a given command in the Pod
```
Usage:   toolbox/local-ci/deploy.sh <ci command> <git repository> <git reference> [gpu_operator_image_tag_uid]
Example: toolbox/local-ci/deploy.sh 'run gpu-ci' https://github.com/openshift-psap/ci-artifacts.git master

toolbox/local-ci/cleanup.sh
```

**Comment by ArangoGutierrez** [comment]
The `build` folder is for things we want into the container image, for this idea I would prefer a simple Bash on the project root.
But I like the idea

**Comment by kpouget** [comment]
@ArangoGutierrez I think this toolbox can be really useful for people dealing with NFD & GPU Operator, so we should strive to make it more complete and convenient to use. Some ideas of what should be added:

- undeploy NFD from OperatorHub
- better control of NFD channel

- capture entitlement possible issues (list MC resources, make sure that cert/key/rhsm are at the right place, test dnf install kernel-devel ...)
- capture GPU operator possible issues (entitlement ^^, NFD labelling, operator deployment, state of resources in gpu-operator-resources, ...)
- deployment of an entitled cluster (https://gitlab.com/kpouget_psap/deploy-cluster)

And in addition, I think that `build/root/usr/local/bin/run` image entry-point should be updated to rely on the toolbox, so that we don't break the toolbox by mistake

**Comment by kpouget** [comment]
for reference, here are the current functionalities of the toolbox:

```
toolbox/gpu-operator/deploy_from_operatorhub.sh
toolbox/gpu-operator/undeploy_from_operatorhub.sh
toolbox/gpu-operator/deploy_from_commit.sh
toolbox/gpu-operator/undeploy_from_commit.sh
toolbox/gpu-operator/run_ci_checks.yml
toolbox/deploy_nfd_from_operatorhub.sh
toolbox/scaleup_gpu_node.sh
```

**Comment by kpouget** [comment]
> :black_square_button: Entitle the cluster, by passing a PEM file, checking if they should be concatenated or not, etc. And do nothing is the cluster is already entitled

@ArangoGutierrez do you think you can take care of that?

I would like to get rid of this:
```
entitle() {
    # TODO: this should become an ansible playbook properly waiting
    # for the deployment of the entitlement

    if [[ "${SKIP_ENTITLEMENT:-n}" == y ]]; then
        echo "Skipping entitlement (SKIP_ENTITLEMENT=${SKIP_ENTITLEMENT})"
        return
    fi

    PSAP_ENTITLEMENT="/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml"
    if [ ! -f "$PSAP_ENTITLEMENT" ]; then
        echo "FATAL: PSAP entitlement resources not found ($PSAP_ENTITLEMENT)"
        exit 1
    fi

    if ! oc get mc/50-entitlement-pem -oname 2>/dev/null | grep -q 50-entitlement-pem; then
        echo "===> Apply entitlement manifests from ${PSAP_ENTITLEMENT} <=="
        oc create -f "${PSAP_ENTITLEMENT}" && sleep 300
    else
        echo "===> Entitlement already instanciated <=="
    fi
}
```
and replace it with something like this in the CI:
```
PSAP_ENTITLEMENT="/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml"
./toolbox/entitle_cluster.sh --machine-configs $PSAP_ENTITLEMENT
```
or outside of the CI:
```
./toolbox/entitle_cluster.sh --pem /path/to/key.pem
```
which would make sure that the entitlement is correctly created and applied.
